version: '2.1'
services:
        sqldb:
                image: mysql:8
                ports:
                        - '3306:3306'
                expose:
                        - '3306'
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_DATABASE=chronoCharm